# Generated by Django 2.2.2 on 2019-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190622_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='time_open',
            field=models.TimeField(null=True),
        ),
    ]
