# Generated by Django 2.2.2 on 2019-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190622_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='time_close',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
