# Generated by Django 2.2.2 on 2019-06-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_reviewcomment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.CharField(choices=[('Dong Da', 'Dong Da'), ('Ba Dinh', 'Ba Dinh'), ('Thanh Xuan', 'Thanh Xuan'), ('Cau Giay', 'Cau Giay'), ('Long Bien', 'Long Bien'), ('Nam Tu Liem', 'Nam Tu Liem'), ('Hoan Kiem', 'Hoan Kiem'), ('Tay Ho', 'Tay Ho'), ('Hai Ba Trung', 'Hai Ba Trung'), ('Hoang Mai', 'Hoang Mai'), ('Ha Dong', 'Ha Dong'), ('Bac Tu Liem', 'Bac Tu Liem')], max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('Cafe - Dessert', 'Cafe - Dessert'), ('Restaurant', 'Restaurant'), ('Bar - Pub', 'Bar - Pub'), ('Snack', 'Snack')], max_length=30),
        ),
    ]
