# Generated by Django 2.2.2 on 2019-06-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190626_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewItem',
            new_name='RestaurantItem',
        ),
        migrations.RemoveField(
            model_name='restaurantitem',
            name='review',
        ),
        migrations.AddField(
            model_name='restaurantitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant'),
            preserve_default=False,
        ),
    ]
