# Generated by Django 2.2.2 on 2019-06-26 17:14

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190626_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='users/default/default_avatar.jpg', upload_to=main.models.profile_picture_path),
        ),
    ]
