# Generated by Django 2.2.2 on 2019-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190701_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
