# Generated by Django 2.2.2 on 2019-09-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190701_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='district',
        ),
        migrations.AlterField(
            model_name='restaurantitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
